import "dotenv/config";
import { Connection, Keypair, LAMPORTS_PER_SOL } from "@solana/web3.js";
import bs58 from "bs58";
import { appendFileSync, existsSync, readFileSync } from "node:fs";
import { logger } from "../monitoring/logger.js";

/**
 * M3: devnet-only wallet handling. There is no path in this module to a
 * mainnet keypair or mainnet RPC — the SRS's non-negotiable ("no real-money
 * execution without explicit later go-ahead") is enforced structurally here,
 * not just by convention: devnetConnection() hardcodes the devnet cluster.
 */

const ENV_KEY = "SOLANA_WALLET_PRIVATE_KEY";
const ENV_FILE = ".env";

/**
 * Loads the devnet keypair from SOLANA_WALLET_PRIVATE_KEY (base58, as
 * produced by `solana-keygen` or this module itself). If it's missing,
 * generates a brand-new devnet-only keypair and appends it to .env so
 * subsequent runs reuse the same address instead of generating a new one
 * (and needing a fresh airdrop) every time.
 */
export function loadOrCreateWallet(): Keypair {
  const existing = process.env[ENV_KEY];
  if (existing) {
    return Keypair.fromSecretKey(bs58.decode(existing));
  }

  const keypair = Keypair.generate();
  const encoded = bs58.encode(keypair.secretKey);

  const envLine = `\n# Auto-generated by src/execution/wallet.ts — devnet only, no real value.\n${ENV_KEY}=${encoded}\n`;
  if (existsSync(ENV_FILE)) {
    const current = readFileSync(ENV_FILE, "utf8");
    if (!current.includes(ENV_KEY)) {
      appendFileSync(ENV_FILE, envLine);
    }
  } else {
    appendFileSync(ENV_FILE, envLine.trimStart());
  }

  logger.system("generated new devnet wallet", { publicKey: keypair.publicKey.toBase58() });
  return keypair;
}

export function devnetConnection(): Connection {
  const url = process.env.SOLANA_DEVNET_RPC_URL || "https://api.devnet.solana.com";
  return new Connection(url, "confirmed");
}

/** Airdrops devnet SOL if the wallet's balance is below the threshold. Devnet SOL has no value — this is never callable against mainnet. */
export async function ensureFunded(connection: Connection, keypair: Keypair, minLamports = 0.5 * LAMPORTS_PER_SOL): Promise<void> {
  const balance = await connection.getBalance(keypair.publicKey);
  if (balance >= minLamports) {
    logger.system("devnet wallet funded", { publicKey: keypair.publicKey.toBase58(), balanceSol: balance / LAMPORTS_PER_SOL });
    return;
  }
  logger.system("requesting devnet airdrop", { publicKey: keypair.publicKey.toBase58() });
  const signature = await connection.requestAirdrop(keypair.publicKey, LAMPORTS_PER_SOL);
  await connection.confirmTransaction(signature, "confirmed");
  const newBalance = await connection.getBalance(keypair.publicKey);
  logger.system("devnet airdrop confirmed", { publicKey: keypair.publicKey.toBase58(), balanceSol: newBalance / LAMPORTS_PER_SOL });
}
